/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import bll.FotoBll;
import java.awt.Image;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Fotos;

/**
 *
 * @author roger
 */
public class ListaDeMiniaturasView extends javax.swing.JDialog {

    Fotos foto = new Fotos();
    FotoBll fotoBll = new FotoBll();

    /**
     * Creates new form ListaDeMiniaturasView
     */
    public ListaDeMiniaturasView(java.awt.Frame parent, boolean modal) throws Exception {
        super(parent, modal);
        initComponents();
        imprimirFotos(fotoBll.getConsultar());
    }

    private void imprimirFotos(List<Fotos> listaFotos) throws Exception {
        DefaultTableModel model = (DefaultTableModel) jTableListaDeMiniaturas.getModel();
        model.setNumRows(0);
        fotoBll.ordenaListaFotos(listaFotos);
        for (int pos = 0; pos < listaFotos.size(); pos++) {
            String[] linha = new String[3];
            Fotos aux = listaFotos.get(pos);
            linha[0] = aux.getId() + "";
            linha[1] = aux.getMiniatura().getModelo_min().toUpperCase();
            linha[2] = String.format("%.2f", aux.getMiniatura().getValor_min()) + "";
            model.addRow(linha);
        }
        jTextFieldQuantRegistros.setText(listaFotos.size() + "");
    }

    private void preencherCampos(int id) throws Exception {
        try {
            if (id > 0) {
                foto = fotoBll.consultarPorId(id);
                jTextFieldModelo.setText(foto.getMiniatura().getModelo_min().toUpperCase());
                jTextFieldAno.setText(foto.getMiniatura().getAno_min() + "");
                jTextFieldObservacao.setText(foto.getMiniatura().getObservacoes_min());
                jTextFieldEdicao.setText(foto.getMiniatura().getEdicao_min());
                jTextFieldEscala.setText(foto.getMiniatura().getEscala_min());
                jTextFieldValor.setText(String.format("%.2f", foto.getMiniatura().getValor_min()) + "");
                jTextFieldFabricante.setText(foto.getMiniatura().getFabricante().getNome().toUpperCase());
                jTextFieldTipoMiniatura.setText(foto.getMiniatura().getTipoMin().getTipo().toUpperCase());
                jTextFieldTema.setText(foto.getMiniatura().getTema().getNome().toUpperCase());
                jTextField1Descricao.setText(foto.getDescricao().toUpperCase());
                jTextFieldCaminhoDoArquivo.setText(foto.getPath());
                // código para redimencionar a imagem
                ImageIcon imageIcon = new ImageIcon(foto.getPath());
                Image image = imageIcon.getImage();
                Image newimg = image.getScaledInstance(350, 260, java.awt.Image.SCALE_SMOOTH);
                
                ImageIcon icon = new ImageIcon(newimg);
                jLabelExibirFoto.setText("");
                jLabelExibirFoto.setIcon(icon);
                
                
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Atenção!!!" + erro.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelListaDeMiniaturas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaDeMiniaturas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldQuantRegistros = new javax.swing.JTextField();
        jPanelInformaçõesDaMiniatura = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldTema = new javax.swing.JTextField();
        jTextFieldModelo = new javax.swing.JTextField();
        jTextFieldAno = new javax.swing.JTextField();
        jTextFieldObservacao = new javax.swing.JTextField();
        jTextFieldEdicao = new javax.swing.JTextField();
        jTextFieldEscala = new javax.swing.JTextField();
        jTextFieldValor = new javax.swing.JTextField();
        jTextFieldFabricante = new javax.swing.JTextField();
        jTextFieldTipoMiniatura = new javax.swing.JTextField();
        jTextField1Descricao = new javax.swing.JTextField();
        jPanelFoto = new javax.swing.JPanel();
        jLabelExibirFoto = new javax.swing.JLabel();
        jTextFieldCaminhoDoArquivo = new javax.swing.JTextField();
        jButtonFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("                                   Lista de Miniaturas com seus detalhes");
        setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        setResizable(false);

        jTableListaDeMiniaturas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTableListaDeMiniaturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód.", "Modelo", "Valor"
            }
        ));
        jTableListaDeMiniaturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableListaDeMiniaturasMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableListaDeMiniaturas);
        if (jTableListaDeMiniaturas.getColumnModel().getColumnCount() > 0) {
            jTableListaDeMiniaturas.getColumnModel().getColumn(0).setMinWidth(50);
            jTableListaDeMiniaturas.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableListaDeMiniaturas.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jLabel1.setText("Quant. Registros:");

        jTextFieldQuantRegistros.setEditable(false);

        jPanelInformaçõesDaMiniatura.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Modelo:");

        jLabel3.setText("Ano:");

        jLabel4.setText("Observações:");

        jLabel5.setText("Edição:");

        jLabel6.setText("Escala:");

        jLabel7.setText("Valor R$:");

        jLabel8.setText("Fabricante:");

        jLabel9.setText("Tipo de Miniatura:");

        jLabel10.setText("Tema da Miniatura:");

        jLabel11.setText("Descrição da Foto:");

        jTextFieldTema.setEditable(false);

        jTextFieldModelo.setEditable(false);

        jTextFieldAno.setEditable(false);

        jTextFieldObservacao.setEditable(false);

        jTextFieldEdicao.setEditable(false);

        jTextFieldEscala.setEditable(false);

        jTextFieldValor.setEditable(false);

        jTextFieldFabricante.setEditable(false);

        jTextFieldTipoMiniatura.setEditable(false);

        jTextField1Descricao.setEditable(false);

        javax.swing.GroupLayout jPanelInformaçõesDaMiniaturaLayout = new javax.swing.GroupLayout(jPanelInformaçõesDaMiniatura);
        jPanelInformaçõesDaMiniatura.setLayout(jPanelInformaçõesDaMiniaturaLayout);
        jPanelInformaçõesDaMiniaturaLayout.setHorizontalGroup(
            jPanelInformaçõesDaMiniaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInformaçõesDaMiniaturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInformaçõesDaMiniaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelInformaçõesDaMiniaturaLayout.createSequentialGroup()
                        .addGroup(jPanelInformaçõesDaMiniaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(35, 35, 35)
                        .addGroup(jPanelInformaçõesDaMiniaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldObservacao)
                            .addComponent(jTextFieldEdicao)
                            .addComponent(jTextFieldEscala)
                            .addComponent(jTextFieldFabricante)
                            .addComponent(jTextFieldValor)))
                    .addGroup(jPanelInformaçõesDaMiniaturaLayout.createSequentialGroup()
                        .addGroup(jPanelInformaçõesDaMiniaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(70, 70, 70)
                        .addGroup(jPanelInformaçõesDaMiniaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelInformaçõesDaMiniaturaLayout.createSequentialGroup()
                        .addGroup(jPanelInformaçõesDaMiniaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelInformaçõesDaMiniaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1Descricao)
                            .addComponent(jTextFieldTipoMiniatura)
                            .addComponent(jTextFieldTema))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanelInformaçõesDaMiniaturaLayout.setVerticalGroup(
            jPanelInformaçõesDaMiniaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInformaçõesDaMiniaturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInformaçõesDaMiniaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInformaçõesDaMiniaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInformaçõesDaMiniaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInformaçõesDaMiniaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInformaçõesDaMiniaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldEscala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInformaçõesDaMiniaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInformaçõesDaMiniaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInformaçõesDaMiniaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldTipoMiniatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInformaçõesDaMiniaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInformaçõesDaMiniaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField1Descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelFoto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelExibirFoto.setText("                                A foto da miniatura será exibida aqui");

        javax.swing.GroupLayout jPanelFotoLayout = new javax.swing.GroupLayout(jPanelFoto);
        jPanelFoto.setLayout(jPanelFotoLayout);
        jPanelFotoLayout.setHorizontalGroup(
            jPanelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFotoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelExibirFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelFotoLayout.setVerticalGroup(
            jPanelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFotoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelExibirFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTextFieldCaminhoDoArquivo.setEditable(false);

        jButtonFechar.setText("FECHAR");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelListaDeMiniaturasLayout = new javax.swing.GroupLayout(jPanelListaDeMiniaturas);
        jPanelListaDeMiniaturas.setLayout(jPanelListaDeMiniaturasLayout);
        jPanelListaDeMiniaturasLayout.setHorizontalGroup(
            jPanelListaDeMiniaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaDeMiniaturasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelListaDeMiniaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelListaDeMiniaturasLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldQuantRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonFechar)
                        .addGap(8, 8, 8))
                    .addGroup(jPanelListaDeMiniaturasLayout.createSequentialGroup()
                        .addComponent(jPanelInformaçõesDaMiniatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelListaDeMiniaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldCaminhoDoArquivo))))
                .addContainerGap())
        );
        jPanelListaDeMiniaturasLayout.setVerticalGroup(
            jPanelListaDeMiniaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListaDeMiniaturasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelListaDeMiniaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelInformaçõesDaMiniatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelListaDeMiniaturasLayout.createSequentialGroup()
                        .addComponent(jPanelFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCaminhoDoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelListaDeMiniaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldQuantRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFechar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelListaDeMiniaturas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelListaDeMiniaturas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTableListaDeMiniaturasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListaDeMiniaturasMouseReleased
        // TODO add your handling code here:
        try {
            int linha = jTableListaDeMiniaturas.getSelectedRow();
            Integer codigo = Integer.parseInt(jTableListaDeMiniaturas.getValueAt(linha, 0).toString());
            preencherCampos((int) codigo);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Atenção!!!" + erro.getMessage());
        }
    }//GEN-LAST:event_jTableListaDeMiniaturasMouseReleased

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaDeMiniaturasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaDeMiniaturasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaDeMiniaturasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaDeMiniaturasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    ListaDeMiniaturasView dialog = new ListaDeMiniaturasView(new javax.swing.JFrame(), true);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(ListaDeMiniaturasView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelExibirFoto;
    private javax.swing.JPanel jPanelFoto;
    private javax.swing.JPanel jPanelInformaçõesDaMiniatura;
    private javax.swing.JPanel jPanelListaDeMiniaturas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListaDeMiniaturas;
    private javax.swing.JTextField jTextField1Descricao;
    private javax.swing.JTextField jTextFieldAno;
    private javax.swing.JTextField jTextFieldCaminhoDoArquivo;
    private javax.swing.JTextField jTextFieldEdicao;
    private javax.swing.JTextField jTextFieldEscala;
    private javax.swing.JTextField jTextFieldFabricante;
    private javax.swing.JTextField jTextFieldModelo;
    private javax.swing.JTextField jTextFieldObservacao;
    private javax.swing.JTextField jTextFieldQuantRegistros;
    private javax.swing.JTextField jTextFieldTema;
    private javax.swing.JTextField jTextFieldTipoMiniatura;
    private javax.swing.JTextField jTextFieldValor;
    // End of variables declaration//GEN-END:variables

}
