/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import javax.swing.JOptionPane;

/**
 *
 * @author roger
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        setExtendedState(MAXIMIZED_BOTH);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuBarraCadastros = new javax.swing.JMenu();
        jMenuItemCadFabricantes = new javax.swing.JMenuItem();
        jMenuItemCadTemas = new javax.swing.JMenuItem();
        jMenuItemCadTipoDeMiniaturas = new javax.swing.JMenuItem();
        jMenuItemCadMiniaturas = new javax.swing.JMenuItem();
        jMenuItemFotos = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemRelatorioDeFotos = new javax.swing.JMenuItem();
        jMenuBarraSair = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Controle de Miniaturas");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );

        jMenuBarraCadastros.setText("Manutenção de Cadastros");

        jMenuItemCadFabricantes.setText("Fabricante");
        jMenuItemCadFabricantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadFabricantesActionPerformed(evt);
            }
        });
        jMenuBarraCadastros.add(jMenuItemCadFabricantes);

        jMenuItemCadTemas.setText("Tema");
        jMenuItemCadTemas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadTemasActionPerformed(evt);
            }
        });
        jMenuBarraCadastros.add(jMenuItemCadTemas);

        jMenuItemCadTipoDeMiniaturas.setText("Tipo de Miniatura");
        jMenuItemCadTipoDeMiniaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadTipoDeMiniaturasActionPerformed(evt);
            }
        });
        jMenuBarraCadastros.add(jMenuItemCadTipoDeMiniaturas);

        jMenuItemCadMiniaturas.setText("Miniaturas");
        jMenuItemCadMiniaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadMiniaturasActionPerformed(evt);
            }
        });
        jMenuBarraCadastros.add(jMenuItemCadMiniaturas);

        jMenuItemFotos.setText("Fotos");
        jMenuItemFotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFotosActionPerformed(evt);
            }
        });
        jMenuBarraCadastros.add(jMenuItemFotos);

        jMenuBar1.add(jMenuBarraCadastros);

        jMenu1.setText("Relatórios");

        jMenuItemRelatorioDeFotos.setText("Fotos");
        jMenuItemRelatorioDeFotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelatorioDeFotosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemRelatorioDeFotos);

        jMenuBar1.add(jMenu1);

        jMenuBarraSair.setText("sair");

        jMenuItem5.setText("Sair");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenuBarraSair.add(jMenuItem5);

        jMenuBar1.add(jMenuBarraSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItemCadFabricantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadFabricantesActionPerformed
        
        try {
           new CadFabricantes(this, true).setVisible(true);
            this.setVisible(true);
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jMenuItemCadFabricantesActionPerformed

    private void jMenuItemCadTipoDeMiniaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadTipoDeMiniaturasActionPerformed
        try {
            new CadTipoMiniaturas(this, true).setVisible(true);
            this.setVisible(true);
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jMenuItemCadTipoDeMiniaturasActionPerformed

    private void jMenuItemCadTemasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadTemasActionPerformed
        try {
            new CadTemas(this, true).setVisible(true);
            this.setVisible(true);
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jMenuItemCadTemasActionPerformed

    private void jMenuItemCadMiniaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadMiniaturasActionPerformed
        try {
            new CadMiniaturas(this, true).setVisible(true);
            this.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jMenuItemCadMiniaturasActionPerformed

    private void jMenuItemFotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFotosActionPerformed
        // TODO add your handling code here:
        try {
            
            new CadFotos(this, true).setVisible(true);
            this.setVisible(true);
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jMenuItemFotosActionPerformed

    private void jMenuItemRelatorioDeFotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelatorioDeFotosActionPerformed
        // TODO add your handling code here:
        try {
            new ListaDeMiniaturasView(null, true).setVisible(true);
            this.setVisible(true);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jMenuItemRelatorioDeFotosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuBarraCadastros;
    private javax.swing.JMenu jMenuBarraSair;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItemCadFabricantes;
    private javax.swing.JMenuItem jMenuItemCadMiniaturas;
    private javax.swing.JMenuItem jMenuItemCadTemas;
    private javax.swing.JMenuItem jMenuItemCadTipoDeMiniaturas;
    private javax.swing.JMenuItem jMenuItemFotos;
    private javax.swing.JMenuItem jMenuItemRelatorioDeFotos;
    // End of variables declaration//GEN-END:variables
}
